version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: finanzas_postgres
    restart: always
    environment:
      POSTGRES_DB: finanzas
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: APPPASS01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: finanzas_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    env_file:
      - .env

volumes:
  postgres_data: